### ISSUE TITLE
Error on lando rebuild with lando 3.17

### ISSUE THREAD

**Issue by sebastienserre** [lando/lando#3567]
Hello,

I'm using Lando in the context of my job at Polylang (Multilingual WordPress plugin). When I need to reproduce a customer issue, I'm creating a WordPress website with lando.
The appname is in general the ticket number. Here's a `.lando.yml`example:
```
name: 23883
recipe: wordpress
config:
  webroot: .
  xdebug: true
  database: mariadb
  php: "8.0"
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    hogfrom:
    - appserver
  redis:
    type: redis
    portforward: true
tooling:
  composer:
    service: appserver
proxy:
    pma:
      - pma-23883.lndo.site
    mailhog:
      - mailhog-23883.lndo.site
events:
  post-rebuild:
    - appserver: wp core install --url="https://23883.lndo.site" --title="Website ticket-23883" --admin_user="pll-admin" --admin_password="PolylangXXX" --admin_email="seb@test.fr"
    - appserver: wp user update pll-admin --locale=us_US
    - appserver: wp plugin activate all-in-one-wp-migration all-in-one-wp-migration-unlimited-extension
    - appserver: wp plugin update --all
    - appserver: wp theme update --all
```
Until Lando 3.17 it was working but from my update I've this error:
```
$ lando rebuild --y
pkg/prelude/bootstrap.js:1930
      return wrapper.apply(this.exports, args);
                     ^

TypeError: undefined is not a function
    at Object.getApp (/snapshot/cli/lib/rts.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at node:internal/main/run_main_module:17:47
```
Issue also reported on [Slack](https://devwithlando.slack.com/archives/C2XBSHX8R/p1683879953319929)
